title: Predicting Power Outage Durations
description: Project for DSC 80 at UC San Diego<br>by Adam Cross

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
